services:

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - fpm
    networks:
      default:

  fpm:
    container_name: fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    command: [ "php-fpm" ]
    expose:
      - "9000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - mysqltest
      - minio
    networks:
      default:

  mysql:
    image: mysql:8.0.35
    container_name: mysql
    ports:
      - 23004:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - devdata:/var/lib/mysql
    networks:
      default:

  mysqltest:
    container_name: mysqltest
    image: mysql:8.0.35
    restart: always
    ports:
      - 23005:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: porto-test
    volumes:
      - testdata:/var/lib/mysql
    networks:
      default:

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001" # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      default:

volumes:
  devdata: {}
  testdata: {}
  minio_data: {}

networks:
  default:
